name: Sync Kaggle Notebooks

on:
  schedule:
    - cron: '0 14 * * *'  # Runs daily at 2:00 pm
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install kaggle
      run: pip install kaggle

    - name: Download Kaggle notebook
      env:
        KAGGLE_USERNAME: ${{ secrets.kamnjeng }}
        KAGGLE_KEY: ${{ secrets.50a645e76c845cd81dcda1565ff249f2 }}
      run: kaggle kernels pull <kamnjeng>/<Sentiment Analysis> -p .

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update Kaggle notebooks"
        git push
